version: "3.8"

services:
  web:
    image: ${IMAGE_NAME}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - yii-network

networks:
  yii-network:
    driver: overlay
