name: Deploy to Swarm

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ashwatthama01
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push
        run: |
          docker build -t ashwatthama01/yii-app:latest -f docker/Dockerfile .
          docker push ashwatthama01/yii-app:latest

      - name: Deploy to Swarm
        uses: appleboy/ssh-action@master
        with:
          host: 3.7.254.189
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            export IMAGE_NAME=ashwatthama01/yii-app:latest
            docker stack deploy -c docker/docker-compose.swarm.yml yii-app --with-registry-auth
            docker service update --force yii-app_web
